from .main import dp
from .auth_bot import dp
from .add_bot import dp
from .choose_bot import dp
from .change_proxy import dp
from .add_proxy import dp
from .manage_bot import dp
from .manage_groups import dp
from .manage_messages import dp
from .choose_save_spam import dp